#!/usr/bin/env bun
/**
 * Scans dashboard/ui/dist and writes server/src/ui-bundle.ts — a static map of
 * URL pathname → embedded file path, with each file imported via
 * `with { type: "file" }` so `bun build --compile` bakes the bytes into the
 * binary.
 *
 * Re-run after every UI build.
 */
import { readdir, stat, writeFile, mkdir } from "node:fs/promises";
import { join, relative, dirname } from "node:path";

const here = new URL(".", import.meta.url).pathname;
const DIST = join(here, "../../ui/dist");
const OUT = join(here, "../src/ui-bundle.ts");

async function walk(dir: string): Promise<string[]> {
  const out: string[] = [];
  for (const name of await readdir(dir)) {
    const p = join(dir, name);
    const st = await stat(p);
    if (st.isDirectory()) out.push(...await walk(p));
    else out.push(p);
  }
  return out;
}

const exists = await stat(DIST).then(() => true).catch(() => false);
if (!exists) {
  // Emit an empty bundle so the server still compiles; user gets a clear
  // "UI not built" message at runtime.
  await mkdir(dirname(OUT), { recursive: true });
  await writeFile(OUT, `// Generated by generate-ui-bundle.ts — run \`bun run build:ui\` first.\nexport const uiBundle: Record<string, string> = {};\n`);
  console.error("ui/dist not found — emitted empty bundle");
  process.exit(0);
}

const files = await walk(DIST);
const imports: string[] = [];
const entries: string[] = [];
files.forEach((abs, i) => {
  const rel = relative(DIST, abs).split("\\").join("/");
  const importPath = "../../ui/dist/" + rel;
  const ident = `f${i}`;
  imports.push(`import ${ident} from ${JSON.stringify(importPath)} with { type: "file" };`);
  entries.push(`  ${JSON.stringify("/" + rel)}: ${ident},`);
  if (rel === "index.html") {
    entries.push(`  "/": ${ident},`);
  }
});

const banner = "// Auto-generated by server/scripts/generate-ui-bundle.ts. Do not edit.\n";
await mkdir(dirname(OUT), { recursive: true });
await writeFile(OUT, `${banner}\n${imports.join("\n")}\n\nexport const uiBundle: Record<string, string> = {\n${entries.join("\n")}\n};\n`);
console.log(`Wrote ${OUT} with ${files.length} embedded files`);
