name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Configure '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: |
        Please paste any relevant logs or error messages.
        Run with `KAPSIS_DEBUG=1` for verbose output.
      render: shell

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Linux (Ubuntu/Debian)
        - Linux (Fedora/RHEL)
        - Linux (Arch)
        - Other
    validations:
      required: true

  - type: input
    id: podman-version
    attributes:
      label: Podman Version
      description: Output of `podman --version`
      placeholder: "podman version 5.0.0"
    validations:
      required: true

  - type: input
    id: kapsis-version
    attributes:
      label: Kapsis Version
      description: Output of `git describe --tags` or commit hash
      placeholder: "1.0.0 or commit abc1234"
    validations:
      required: true

  - type: dropdown
    id: agent
    attributes:
      label: Agent Type
      description: Which AI agent were you using?
      options:
        - Claude Code (CLI)
        - Claude Code (API)
        - Aider
        - Codex
        - Gemini
        - Custom/Other
        - Not applicable

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant portions of your agent-sandbox.yaml (remove sensitive data)
      render: yaml

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I have run `./setup.sh --check` and all dependencies are satisfied
          required: false
        - label: I can reproduce this issue consistently
          required: false
