name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Why is it needed?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or feature
      placeholder: I would like to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: I've also thought about...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      options:
        - Agent Support (new AI agents)
        - Container/Isolation
        - Git Integration
        - Configuration
        - CLI/UX
        - Performance
        - Security
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: How big of a change is this?
      options:
        - Small (minor enhancement)
        - Medium (new feature)
        - Large (significant new capability)
        - Breaking (requires migration)
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to contribute this feature
          required: false
        - label: I have searched existing issues/PRs for similar requests
          required: true
